### ISSUE TITLE
Search_catalog() returning no results for published dataset

### ISSUE THREAD

**Issue by alpaziz** [tonyfujs/ddhconnect#102]
For published dataset "Education Statistics" the `search_catalog()` isn't returning any results:
![image](https://user-images.githubusercontent.com/23365560/52888794-1c61f200-314b-11e9-9b1c-905304dbd0ac.png)

![image](https://user-images.githubusercontent.com/23365560/52888832-41566500-314b-11e9-9a6a-2fa26b227a45.png)

**Comment by tonyfujs** [comment]
This a DDH API problem, not a ddhconnect one. See JIRA DDH2-291
