### ISSUE TITLE
Error: Result 25524 is not a length 1 atomic vector

### ISSUE THREAD

**Issue by Yukun1218** [tonyfujs/ddhconnect#67]
https://github.com/tonyfujs/ddhconnect/blob/fc3ee717df2901c03da3cd60dad6d9eacfdeae1c/R/get_datasets_list.R#L36

**Comment by seladore** [comment]
hi @Yukun1218, I wasn't able to recreate this issue. Is it still a problem for you?

**Comment by Yukun1218** [comment]
Hi Meera, let me check on Monday! 😊

**Comment by Yukun1218** [comment]
Let's close it for now, I couldn't recreate it neither.
