### ISSUE TITLE
Add authentication to function calling internal/xxxx endpoints

### ISSUE THREAD

**Issue by tonyfujs** [tonyfujs/ddhconnect#77]
With the move to the cloud, these functions will break without authentication

**Comment by alpaziz** [comment]
The two functions which have 'internal' in their paths are 'get_user_details()' and 'get_fields(),' and both of them already have authentication:
 
 
![image](https://user-images.githubusercontent.com/23365560/51042236-c6b58b00-1589-11e9-946f-bb2529aa034b.png)

![image](https://user-images.githubusercontent.com/23365560/51042269-dd5be200-1589-11e9-807b-d7004b15314c.png)
